# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/trltexx/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/trltexx/proprietary/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
    vendor/samsung/trltexx/proprietary/bin/bridgemgrd:system/bin/bridgemgrd \
    vendor/samsung/trltexx/proprietary/bin/port-bridge:system/bin/port-bridge \
    vendor/samsung/trltexx/proprietary/bin/cnd:system/bin/cnd \
    vendor/samsung/trltexx/proprietary/vendor/lib/libcne.so:system/vendor/lib/libcne.so \
    vendor/samsung/trltexx/proprietary/bin/imsdatadaemon:system/bin/imsdatadaemon \
    vendor/samsung/trltexx/proprietary/bin/imsqmidaemon:system/bin/imsqmidaemon \
    vendor/samsung/trltexx/proprietary/bin/ims_rtp_daemon:system/bin/ims_rtp_daemon \
    vendor/samsung/trltexx/proprietary/bin/tcmd_mini:system/bin/tcmd_mini \
    vendor/samsung/trltexx/proprietary/etc/permissions/rcsimssettings.xml:system/etc/permissions/rcsimssettings.xml \
    vendor/samsung/trltexx/proprietary/etc/permissions/rcsservice.xml:system/etc/permissions/rcsservice.xml \
    vendor/samsung/trltexx/proprietary/lib/libimscamera_jni.so:system/lib/libimscamera_jni.so \
    vendor/samsung/trltexx/proprietary/app/ims/lib/arm/libimscamera_jni.so:system/app/ims/lib/arm/libimscamera_jni.so \
    vendor/samsung/trltexx/proprietary/lib/libimsmedia_jni.so:system/lib/libimsmedia_jni.so \
    vendor/samsung/trltexx/proprietary/app/ims/lib/arm/libimsmedia_jni.so:system/app/ims/lib/arm/libimsmedia_jni.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/lib-dplmedia.so:system/vendor/lib/lib-dplmedia.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/lib-imsSDP.so:system/vendor/lib/lib-imsSDP.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/lib-imsdpl.so:system/vendor/lib/lib-imsdpl.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/lib-imsqimf.so:system/vendor/lib/lib-imsqimf.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/lib-imsrcs.so:system/vendor/lib/lib-imsrcs.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/lib-imss.so:system/vendor/lib/lib-imss.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/lib-imsvt.so:system/vendor/lib/lib-imsvt.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/lib-imsxml.so:system/vendor/lib/lib-imsxml.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/lib-rcsimssjni.so:system/vendor/lib/lib-rcsimssjni.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/lib-rcsjni.so:system/vendor/lib/lib-rcsjni.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/lib-rtpcommon.so:system/vendor/lib/lib-rtpcommon.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/lib-rtpcore.so:system/vendor/lib/lib-rtpcore.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/lib-rtpdaemoninterface.so:system/vendor/lib/lib-rtpdaemoninterface.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/lib-rtpsl.so:system/vendor/lib/lib-rtpsl.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/libvcel.so:system/vendor/lib/libvcel.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/libflp.so:system/vendor/lib/libflp.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/libdataitems.so:system/vendor/lib/libdataitems.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/liblowi_client.so:system/vendor/lib/liblowi_client.so \
    vendor/samsung/trltexx/proprietary/lib/libagc_max.so:system/lib/libagc_max.so \
    vendor/samsung/trltexx/proprietary/lib/libqservice.so:system/lib/libqservice.so \
    vendor/samsung/trltexx/proprietary/lib/libtinyxml.so:system/lib/libtinyxml.so \
    vendor/samsung/trltexx/proprietary/lib/libqdutils.so:system/lib/libqdutils.so \
    vendor/samsung/trltexx/proprietary/lib/libjpegehw.so:system/lib/libjpegehw.so \
    vendor/samsung/trltexx/proprietary/lib/libjpegdhw.so:system/lib/libjpegdhw.so \
    vendor/samsung/trltexx/proprietary/lib/libedmnativehelper.so:system/lib/libedmnativehelper.so \
    vendor/samsung/trltexx/proprietary/lib/libbt-iopdb.so:system/lib/libbt-iopdb.so \
    vendor/samsung/trltexx/proprietary/lib/libbt-iopdb_mod.so:system/lib/libbt-iopdb_mod.so \
    vendor/samsung/trltexx/proprietary/lib/libbt-vendor.so:system/vendor/lib/libbt-vendor.so \
    vendor/samsung/trltexx/proprietary/lib/libbt-codec_aptx.so:system/lib/libbt-codec_aptx.so \
    vendor/samsung/trltexx/proprietary/lib/libbt-aptX-ARM-4.2.2.so:system/lib/libbt-aptX-ARM-4.2.2.so \
    vendor/samsung/trltexx/proprietary/lib/libbt-codec_sshd.so:system/lib/libbt-codec_sshd.so \
    vendor/samsung/trltexx/proprietary/lib/libshdace.so:system/lib/libshdace.so \
    vendor/samsung/trltexx/proprietary/lib/libprotobuf-cpp-full.so:system/lib/libprotobuf-cpp-full.so \
    vendor/samsung/trltexx/proprietary/bin/efsks:system/bin/efsks \
    vendor/samsung/trltexx/proprietary/bin/ks:system/bin/ks \
    vendor/samsung/trltexx/proprietary/bin/mdm_helper:system/bin/mdm_helper \
    vendor/samsung/trltexx/proprietary/bin/mdm_helper_proxy:system/bin/mdm_helper_proxy \
    vendor/samsung/trltexx/proprietary/bin/qcks:system/bin/qcks \
    vendor/samsung/trltexx/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/samsung/trltexx/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/samsung/trltexx/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/samsung/trltexx/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/libmdmcutback.so:system/vendor/lib/libmdmcutback.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/libqmimotext.so:system/vendor/lib/libqmimotext.so \
    vendor/samsung/trltexx/proprietary/lib/libmdmdetect.so:system/lib/libmdmdetect.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/libmotext_inf.so:system/vendor/lib/libmotext_inf.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/libsysutils_local.so:system/vendor/lib/libsysutils_local.so \
    vendor/samsung/trltexx/proprietary/vendor/lib/libuiblur.so:system/vendor/lib/libuiblur.so
